#
# University of Pisa - Advanced Software Engineering - 2021-2022
# Main docker-compose File
# Project:
#┌─────────────────────────────────────────────────────────────────────────────────────────┐ 
#│  __  __                                  _                 ____        _   _   _        │ 
#│ |  \/  | ___  ___ ___  __ _  __ _  ___  (_)_ __     __ _  | __ )  ___ | |_| |_| | ___   │
#│ | |\/| |/ _ \/ __/ __|/ _` |/ _` |/ _ \ | | '_ \   / _` | |  _ \ / _ \| __| __| |/ _ \  │
#│ | |  | |  __/\__ \__ \ (_| | (_| |  __/ | | | | | | (_| | | |_) | (_) | |_| |_| |  __/  │ 
#│ |_|  |_|\___||___/___/\__,_|\__, |\___| |_|_| |_|  \__,_| |____/ \___/ \__|\__|_|\___|  │ 
#│                              |___/                                                      │ 
#└─────────────────────────────────────────────────────────────────────────────────────────┘

version: '3.8'

services:
  
  # -------------------------------------------- #
  # Starting with API Gateway and Load Balancer  #
  # -------------------------------------------- #
 
  nginx_lb_orchestrator:
    #
    # Nginx Orchestrator instance
    #
    container_name: load_balancer_orchestrator
    restart: always
    build: ./MMIB-ApiGateway-Submodule/nginx-orchestrator
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # WARNING: with Winzozz it does not work, but we need it!
      - nginx_conf:/etc/nginx/conf.d

  nginx_lb:
    #
    # Nginx single instance
    #
    container_name: load_balancer
    restart: always
    build: ./MMIB-ApiGateway-Submodule/nginx
    labels:
      - mib.nginx_lb
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - static_contents:/static
    ports:
      - "80:80"

  api_gateway:
    #
    # API Gateway
    #
    # ! ! ! WARNING ! ! !
    # DO NOT set the container_name attribute and ports mapping
    # to allow the replication.
    #
    restart: always
    build: ./MMIB-ApiGateway-Submodule
    volumes:
      - static_contents:/static
    env_file:
      - gateway.conf
    environment:
      - USERS_MS_HOST=users_ms_worker
      - NOTIFICATIONS_MS_HOST=notifications_ms_worker
    labels:
      - mib.api_gateway_worker

  # -------------------------------------------- #
  # Common Services                              #
  # -------------------------------------------- #
  
  #
  # specify here the common services between your
  # microservices
  #


  # -------------------------------------------- #
  # Users Microservice                           #
  # -------------------------------------------- #

  users_ms_worker:
    #
    # Users Microservice Worker node
    #
    build: ./Users-Service
    restart: on-failure


  # -------------------------------------------- #
  # Notifications Microservice                   #
  # -------------------------------------------- #

  notifications_ms_worker:
    #
    # Users Microservice Worker node
    #
    build:
      context: ./notifications-service
      dockerfile: DockerfileWeb
    restart: on-failure
    volumes:
      - ./notifications-service:/code

  redis:
    image: "redis:alpine"
    container_name: rd01
    expose:
      - "6379"
    restart: on-failure
  
  celery:
    depends_on:
      - redis
    build: 
      context: ./notifications-service
      dockerfile: DockerfileCelery
    links:
      -  redis
    volumes:
      - ./notifications-service:/code/
    restart: on-failure

  #
  # Specify here your microservices
  # separating services by: db_service, migration_service, worker_service
  #

volumes:
  # -------------------------------------------- #
  # Volumes                                      #
  # -------------------------------------------- #

  nginx_conf:
  # Nginx configuration volume

  static_contents:
  # API Gateway static content volume

